-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgI9SGsuowbPTkFh+t
WONYbXOIrweLkpJWOK5y5O+X1yKgCgYIKoZIzj0DAQehRANCAAT1l0+uQoM9YyOj
mG2yhKkp0ad1FULnh/Dho7oq/xy3CAC2Ukqa6XQ/Yz9KXDMraBV6wtLJehz4A1WA
+wCeKzMU
-----END PRIVATE KEY-----