# 1
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"
ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']= 'eqmy-izsr-famb-agvb'
ENV['FASTLANE_USER']= 'itune.hasam@gmail.com'
ENV['FASTLANE_PASSWORD']= '6@hsu307^ayehnmoY'
# 2
default_platform(:ios)
# 3
platform :ios do
  # 4
  lane :build do
    cert
    sigh
    gym
  end
  lane :test do
    scan
  end
  lane :alpha do
    # 1
    build
    # 2
    pilot
    # 3
    increment_build_number
  end
  lane :release do
    # 1
    build
    # 2
    deliver
    # 3
    increment_build_number
  end
end