# 1
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"
ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']= 'eqmy-izsr-famb-agvb'

# 2
default_platform(:ios)
# 3
platform :ios do
  # 4
  lane :build do
    cert
    sigh
    gym
  end
  lane :test do
    scan
  end
  lane :alpha do
    # 1
    build
    # 2
    api_key = app_store_connect_api_key(
      key_id: "T2TM8TLBCV",
      issuer_id: "3bfff8be-a470-48b5-9d2f-7ed90a062e21",
      key_content: "Base64_encode_of_-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgI9SGsuowbPTkFh+t
WONYbXOIrweLkpJWOK5y5O+X1yKgCgYIKoZIzj0DAQehRANCAAT1l0+uQoM9YyOj
mG2yhKkp0ad1FULnh/Dho7oq/xy3CAC2Ukqa6XQ/Yz9KXDMraBV6wtLJehz4A1WA
+wCeKzMU\n-----END PRIVATE KEY-----",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    match(      
      type: 'appstore', 
      app_identifier: ["com.hieunguyen.eng.vocab"],
      api_key: api_key,
      readonly: true
    )
    pilot(api_key: api_key)
    # 3
    increment_build_number
  end
  lane :release do
    # 1
    build
    # 2
    api_key = app_store_connect_api_key(
      key_id: "T2TM8TLBCV",
      issuer_id: "3bfff8be-a470-48b5-9d2f-7ed90a062e21",
      key_content: "Base64_encode_of_-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgI9SGsuowbPTkFh+t
WONYbXOIrweLkpJWOK5y5O+X1yKgCgYIKoZIzj0DAQehRANCAAT1l0+uQoM9YyOj
mG2yhKkp0ad1FULnh/Dho7oq/xy3CAC2Ukqa6XQ/Yz9KXDMraBV6wtLJehz4A1WA
+wCeKzMU\n-----END PRIVATE KEY-----",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    match(      
      type: 'appstore', 
      app_identifier: ["com.hieunguyen.eng.vocab"],
      api_key: api_key,
      readonly: true
    )
    pilot(api_key: api_key)
    # 3
    increment_build_number
  end
end